### ISSUE TITLE
GPIO 0 appears to not be controllable

### ISSUE THREAD

**Issue by IARI** [catgiggle/OctoPrint-GpioControl#20]
I am trying to get what i so far had solved with octoprints config.yaml with this GpioControl plugin.
So far, this has worked for me:

```yaml
    actions:
    -   action: printerOn
        command: gpio mode 7 out; gpio write 7 0
        name: Printer On
    -   action: printerOff
        command: gpio mode 7 out; gpio write 7 1
        name: Printer Off
    -   action: fanOn
        command: gpio mode 0 out; gpio write 0 1
        name: Fan On
    -   action: fanOff
        command: gpio mode 0 out; gpio write 0 0
        name: Fan Off
```
Trying to implement it with this plugin:
![image](https://user-images.githubusercontent.com/1053417/110462235-b1d4d380-80d0-11eb-8a82-004e4bb4619e.png)

But the button is gray

![image](https://user-images.githubusercontent.com/1053417/110461813-35da8b80-80d0-11eb-88a2-fc0e29f2e847.png)

what could be the problem?
